
<body id="body">
	<form method="post" action="/auth/identify" id="formLogin" name="formLogin">
	<?php
	echo $this->partial('index/header_naologado.phtml', array('actionErrors'=>$this->actionErrors,'auth'=>$this->auth));
	?>
	<!--/#header-->
	<div id="container">
		<div id="wrapper">
						
    <div id="ContentPlaceHolder_Body_upLogin">
	
            <div class="content content_login">
                <div class="inner">
                    <fieldset class="f_login">
                        <h2 class="fonte700">
                            LOGIN</h2>
                        <ul class="fields"> 
                            <li>
                                <label for="ContentPlaceHolder_Body_txtIdentificacao" id="ContentPlaceHolder_Body_lblIdentificacao">Identificação:</label>
                                <div class="fieldbox">
                                    <input name="txtLoginEmail" type="text" maxlength="50" id="iptTxtLogin" class="textbox" />
                                </div>
                            </li>
                            <li>
                                <label for="ContentPlaceHolder_Body_txtSenha" id="ContentPlaceHolder_Body_lblSenha">Senha:</label>
                                <div class="fieldbox">
                                    <input name="pwdLoginSenha" type="password" maxlength="10" id="iptTxtSenha" class="textbox" />
                                </div>
                                <p>
                                    <a id="ContentPlaceHolder_Body_lnkEsqueciSenha" href="/auth/esqueci">Esqueci minha senha</a>
                                </p>
                            </li>
                            <li class="buttons">
                                <a id="ContentPlaceHolder_Body_btnLogin" class="btn_ok" href="javascript:document.formLogin.submit()">Entrar</a>
                            </li>
                        </ul>
                    </fieldset>
                    <span id="ContentPlaceHolder_Body_ctvLogin" style="display:none;"></span>
                </div>
            </div>
        
</div>

		</div>
		<!--/#wrapper-->
	</div>
	<!--/#container-->
	
<?php
echo $this->partial('index/footer.phtml');
?>
	
</form>
</body>
</html>
