</form>
<div id="footer">
    <div id="footerCont">
        <ul>
            <li><a href="politica-privacidade">Política de Privacidade</a></li>
            <li>|</li>
            <li><a href="termos">Termos e Condições de Uso</a></li>
        </ul>
        <div id="copyright">Copyright 2012 Evimail - Design e Desenvolvimento: <a href="http://www.marlin.com.br/" target="_blank">Marlin</a></div>
    </div>
</div>
	<!--/#footer-->
