<div id="header" class="headerNaoLogado">
	
    <div id="headerCont">
        <h1 id="logo"><a href="/">Evimail Evidência</a></h1>
        <div id="menuHeader">
		<ul class="level1">
			<li><a class="level1" href="/">Home</a></li><li><a class="level1" href="QuemSomos.html">Quem Somos</a></li><li><a class="level1" href="PerguntasFrequentes.html">Perguntas Frequentes</a></li><li><a class="level1" href="FaleConosco.html">Fale Conosco</a></li>
		</ul>
		</div>
        <div id="pnlNaoLogado">
		
            <div class="left">
                <span>Já é cliente?</span>
                <a id="lnkLogar" href="/auth">Faça seu login</a>
            </div>
            <div class="right">
                <span>Novo usuário?</span>
                <a id="lnkCadastrar" href="/cadastro"></a>
            </div>
        
		</div>
        
    </div>
    <!--/#headerCont-->
	</div>
	<!--/#header-->