<?php
echo $this->partial('index/header_naologado.phtml', array('actionErrors'=>$this->actionErrors,'auth'=>$this->auth, 'user' => $this->user, 'classPrinc'=>'inner vantagens'));
?>
	<div id="container">
		<div id="wrapper">

			
    <div id="content">
        <h2 class="title">Vantagens pra você e sua empresa</h2>
        <div class="entryContent">
            <h3>loren Ipsun Dolor</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sed urna in sem ultricies pretium. Maecenas laoreet consequat dui nec facilisis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis ac fringilla sem. Vestibulum nulla tortor, lobortis in blandit eu, fermentum id nisi. Etiam a nulla eu lorem rhoncus congue quis ac magna. Sed blandit blandit quam in scelerisque. Vivamus semper elit vitae libero aliquet et sodales massa rhoncus. Integer ac bibendum erat.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sed urna in sem ultricies pretium. Maecenas laoreet consequat dui nec facilisis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis ac fringilla sem. Vestibulum nulla tortor, lobortis in blandit eu, fermentum id nisi. Etiam a nulla eu lorem rhoncus congue quis ac magna. Sed blandit blandit quam in scelerisque. Vivamus semper elit vitae libero aliquet et sodales massa rhoncus. Integer ac bibendum erat.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sed urna in sem ultricies pretium. Maecenas laoreet consequat dui nec facilisis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis ac fringilla sem. Vestibulum nulla tortor, lobortis in blandit eu, fermentum id nisi. Etiam a nulla eu lorem rhoncus congue quis ac magna. Sed blandit blandit quam in scelerisque. Vivamus semper elit vitae libero aliquet et sodales massa rhoncus. Integer ac bibendum erat.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sed urna in sem ultricies pretium. Maecenas laoreet consequat dui nec facilisis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis ac fringilla sem. Vestibulum nulla tortor, lobortis in blandit eu, fermentum id nisi. Etiam a nulla eu lorem rhoncus congue quis ac magna. Sed blandit blandit quam in scelerisque. Vivamus semper elit vitae libero aliquet et sodales massa rhoncus. Integer ac bibendum erat.</p>
        </div>
    </div>

		</div>
		<!--/#wrapper-->
	</div>
	<!--/#container-->
	
<?php
echo $this->partial('index/footer.phtml');
?>

	
<script type='text/javascript'>new Sys.WebForms.Menu({ element: 'menuHeader', disappearAfter: 500, orientation: 'vertical', tabIndex: 0, disabled: false });</script></form>
	<script type="text/javascript">        Cufon.now(); </script>
</body>
</html>
