<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!--meta http-equiv="Content-Type" content="text/html; charset=utf-8" /-->
    <title>Newsletter Evimail</title>
</head>
<body bgcolor="#3b4652" leftmargin="0" topmargin="0" rightmargin="0" bottommargin="0"
    marginwidth="0" marginheight="0">
    <table width="946" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#3b4652">
        <tr>
            <td bgcolor="#3b4652">
                &nbsp;
            </td>
            <td width="768" bgcolor="#e8ebed">
                <table width="768" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td colspan="7" width="303">
                            <a href="http://www.evimail.com.br" target="_blank"><img src="<?=$this->data['url']?>/img/imgEmail/logo.png" border="0" width="303" height="123" alt="Evimail - Confirmação de pedido" title="Evimail - Confirmação de pedido" style="display: block;" /></a>
                        </td>
                        <td width="419" valign="bottom" align="right" style="font: bold 30px Trebuchet MS;
                            color: #3b4652;">
                            Esqueci minha senha
                        </td>
                        <td align="right">
                            <img src="<?=$this->data['url']?>/img/imgEmail/spacer.gif" width="37" height="1" alt="Evimail - Confirmação de pedido"
                                style="display: block;" />
                        </td>
                    </tr>
                </table>
                <table width="768" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td colspan="7">
                            <img src="<?=$this->data['url']?>/img/imgEmail/topo.jpg" width="768" height="30" alt="Evimail - Confirmação de pedido"
                                title="Evimail - Confirmação de pedido" style="display: block;" />
                        </td>
                    </tr>
                    <tr>
                        <td width="36" style="background-color: #e7ebee;">
                            &nbsp;
                        </td>
                        <td width="1" style="background-color: #d8d8d8;">
                        </td>
                        <td width="24" style="background-color: #ffffff;">
                            &nbsp;
                        </td>
                        <td style="background-color: #ffffff;" width="643">
                            <font face="Trebuchet MS, Arial, Helvetica, sans-serif" color="#576470">
                                <p>
                                    <font size="5">Prezado(a) <?=$this->data['usr_name']?>!</font></p>
                                    <p>
                                    <font size="4">Você está recebendo este e-mail pois solicitou a recuperação de senha.</font></p>
                                <p>
                                    <font size="4">Seu login é <?=$this->data['usr_nickname']?><strong></strong></font>.<br />
                                    <font size="4">Sua nova senha é <?=$this->data['passwd']?><strong></strong></font>.
                                </p><br />                            
                            </font>
                        </td>
                        <td width="24" style="background-color: #ffffff;">
                            &nbsp;
                        </td>
                        <td width="1" style="background-color: #d8d8d8;">
                        </td>
                        <td width="39" style="background-color: #e7ebee;">
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td colspan="7">
                            <img src="<?=$this->data['url']?>/img/imgEmail/rodape.jpg" width="768" height="75" alt="Transforme seu email em EVIDÊNCIA - www.evimail.com.br" title="Transforme seu email em EVIDÊNCIA - www.evimail.com.br" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="7" height="170">
                            &nbsp;
                        </td>
                    </tr>
                </table>
            </td>
            <td bgcolor="#3b4652">
                &nbsp;
            </td>
        </tr>
    </table>
</body>
</html>
