<body id="body" class="inner cadastro">
<?php
echo $this->partial('index/header_logado.phtml', array('actionErrors'=>$this->actionErrors,'auth'=>$this->auth, 'menu'=>'historico', 'user' => $this->user));
?>
	<div id="container">
		<div id="wrapper">			   
    <div id="content">
    <form method="post" action="/minha-conta/consultar-historico" id="form1">
        <h2 class="title">
            Consultar Histórico de Emails</h2>
        <div id="procurarEmail">
            <h5 class="title_1">
                Procurar e-mail:</h5>
            <div class="rounded_a">
                <div id="ContentPlaceHolder_Body_vldsmyHistorico" style="display:none;">

</div>
                <fieldset>
                    <div class="campoHistorico">
                        <label for="ContentPlaceHolder_Body_ddlDirecao" id="ContentPlaceHolder_Body_lblDirecao" class="lblTextbox">Direção</label>
                        <select name="direcao" id="ContentPlaceHolder_Body_ddlDirecao">
	<option value="0">Indiferente</option>
	<option value="1">Enviado</option>
	<option value="2">Recebido</option>

</select>
                    </div>
                    <div class="campoHistorico">
                        <label for="ContentPlaceHolder_Body_txtAssunto" id="ContentPlaceHolder_Body_lblAssunto" class="lblTextbox">Assunto:</label>
                        <input name="subject" type="text" maxlength="40" id="ContentPlaceHolder_Body_txtAssunto" class="textbox" />
                    </div>
                    <div class="campoHistorico">
                        <div id="ContentPlaceHolder_Body_pnlRemetente">
	
                            <label for="ContentPlaceHolder_Body_txtRemetente" id="ContentPlaceHolder_Body_lblRemetente" class="lblTextbox">Remetente:</label>
                            <input name="from" type="text" maxlength="40" id="ContentPlaceHolder_Body_txtRemetente" class="textbox" />
                        
</div>
                    </div>
                    <div class="campoHistorico">
                        <label for="ContentPlaceHolder_Body_txtDestinatario" id="ContentPlaceHolder_Body_lblDestinatario" class="lblTextbox">Destinatário:</label>
                        <input name="to" type="text" maxlength="40" id="ContentPlaceHolder_Body_txtDestinatario" class="textbox" />
                    </div>
                    <div class="campoHistorico">
                        <label for="ContentPlaceHolder_Body_ddlAnexos" id="ContentPlaceHolder_Body_lblAnexos" class="lblTextbox">Anexos</label>
                        <select name="anexos" id="ContentPlaceHolder_Body_ddlAnexos">
	<option value="0">Indiferente</option>
	<option value="1">Sem Anexos</option>
	<option value="2">Com Anexos</option>

</select>
                    </div>
                    <div class="campoHistorico">
                        <label for="ContentPlaceHolder_Body_ddlStatus" id="ContentPlaceHolder_Body_lblStatus" class="lblTextbox">Status:</label>
                        <select name="status" id="ContentPlaceHolder_Body_ddlStatus">
	<option value="">Indiferente</option>
	<option value="0">Pendente</option>
	<option value="2">Confirmado</option>
<!-- 	<option value="0">Recebido</option> -->
<!-- 	<option value="2">Confirmado - Conte&#250;do</option> -->
<!-- 	<option value="2">Confirmado - Anexos</option> -->
<!-- 	<option value="2">Confirmado - Conte&#250;do e Anexos</option> -->

</select>
                    </div>
                    <div>
                        <label for="ContentPlaceHolder_Body_txtDataInicial" id="ContentPlaceHolder_Body_lblDataIni" class="lblTextbox">Período de:</label>
                        <input name="dt_ini" type="text" id="ContentPlaceHolder_Body_txtDataInicial" class="textbox txtDataIni" />
                        <a id="ContentPlaceHolder_Body_calendar_ini" title="Calendario" href="javascript:__doPostBack(&#39;ctl00$ContentPlaceHolder_Body$calendar_ini&#39;,&#39;&#39;)"> 
                            <img src="../img/ico_calendar.gif" width="32" height="28" alt="Calendario" style="margin:0 9px 0 0; vertical-align:bottom; " />                             
                        </a>
                        
                        <span id="ContentPlaceHolder_Body_RegularExpressionValidator1" style="visibility:hidden;">Data inválida</span>
                        <label for="ContentPlaceHolder_Body_txtDataFinal" id="ContentPlaceHolder_Body_lblDataFim">a</label>
                        <input name="dt_fim" type="text" id="ContentPlaceHolder_Body_txtDataFinal" class="textbox txtDataFim" />
                        <a id="ContentPlaceHolder_Body_calendar_fim" title="Calendario" href="javascript:__doPostBack(&#39;ctl00$ContentPlaceHolder_Body$calendar_fim&#39;,&#39;&#39;)">   
                            <img src="../img/ico_calendar.gif" width="32" height="28" alt="Calendario" style="margin:0 9px 0 0; vertical-align:bottom; " />                        
                        </a>
                        
                        <span id="ContentPlaceHolder_Body_RegularExpressionValidator2" style="visibility:hidden;">Data inválida</span>
                    </div>
                    <div class="btnContLine">
                        <span id="ContentPlaceHolder_Body_lblErro"></span>
                        <a id="procurar" class="btnProcurar" href="javascript:;">Procurar</a>
                    </div>
                </fieldset>
            </div>
        </div>
        </form>
        <!--/#procurarEmail-->
        <div style="text-align: center;">
            
        </div>
        <div class="row">
                                <table class="tableStyle">
                        <thead>
                            <tr>
                                <th align="center">
                                    DATA
                                </th>
                                <th align="left">
                                    Remetente
                                </th>
                                <th align="left">
                                    Destinatário
                                </th>
                                <th align="left">
                                    Assunto
                                </th>
                                <th align="center">
                                    Anexos
                                </th>
                                <th align="center">
                                    PDF
                                </th>
                                <th align="center">
                                    Entregue
                                </th>
                                <th align="center">
                                    Conteúdo
                                </th>
<!--                                <th align="center">
                                    Enviado/ recebido
                                </th>-->
                            </tr>
                        </thead>
                    <tbody runat="server" id="itemPlaceholder">
                    <?php foreach($this->emails as $email) {?> 
                    <tr class="tableStyle">
                        <!--<tr class="linhaHistoricoDesSelecionada" onmouseover="this.className='linhaHistoricoSelecionada'" onmouseout="this.className='linhaHistoricoDesSelecionada'">-->
                        <td align="center">
                        <?php echo $email->ema_DateFormatado?>
			</td>
                        <td align="left">
                        <?php echo $email->ema_emailfrom?>
			</td>
                        <td align="left">
                        <?php echo $email->ema_emailto?>
			</td>
                        <td align="left">
                        <?php echo $email->ema_subject?>
			</td>
                        <td align="center">
                        	<a href="minha-conta/lista-anexos/<?php echo $this->user->usr->id.'/'.$email->ema_hash?>">
			    			<img src="/img/ico_anexo.gif" border="0">
			    			</a>
                        </td>
                        <td align="center">
                        	<a href="/minha-conta/download-pdf/ema_hash/<?php echo $email->ema_hash?>">
			    			<img src="/img/icone-pdf.png" border="0">
			    			</a>
                        </td>
                        <td align="center">
                        <?php if($email->ema_confirmed == Fet_Model_EmailTable::EMAIL_ENVIADO_DEBITADO) {?>
						    <img src="/img/ico_sim.gif" border="0">
					    <?php }?>
					    <?php if($email->ema_confirmed == Fet_Model_EmailTable::EMAIL_NAO_ENVIADO) {?>
			    			<img src="/img/ico_nao.gif" border="0">
						<?php }?>
                        </td>
                        <td align="center">
			    			<a href="/minha-conta/visualiza-laudo/ema_id/<?php echo $email->ema_id?>"><img src="/img/ico_more.gif" border="0"></a>
                        </td>
                        <!--<td align="center">
                        a
			</td>-->
                    </tr>
 				<?php }?>
                        </tbody>
		</table>
            <div class="pagination">
                <span class="paginationMsg">
                    
                    
                </span>
                <div class="paginationPg">
                    <small>
<img src="/img/ico_pagination_left_arrow.gif" border="0">
<img src="/img/ico_pagination_right_arrow.gif" border="0">
                        </small>
                    <span id="ContentPlaceHolder_Body_dpgMinhaConta"></span>
                </div>
            </div>
            <!--/.pagination-->
        </div>
        <!--/.row-->
    </div>

		</div>
		<!--/#wrapper-->
	</div>
	<!--/#container-->

<script type="text/javascript">
$(document).ready(function() {
	$('#procurar').click(function(){
		$("#form1").submit();
	});
});
</script>	
	
<?php
echo $this->partial('index/footer.phtml');
?>
	